 services:
  web:
    build:
      context: nginx
    command: /bin/bash -c "envsubst < /tmp/secure-site.conf > /etc/nginx/conf.d/secure-site.conf && nginx -g 'daemon off;'"
    ports:
      - 443:443
    environment: 
      - FLASK_SERVER_ADDR=backend:5001 
    depends_on:
      - backend
  backend:
    image: digitalocean/flask-helloworld 
    environment: 
      - FLASK_SERVER_PORT=5001
    # ports:
    #   - 5000:5000
    volumes:
      - ./app:/app


